FROM python:3.12-slim

WORKDIR /app

# Install system dependencies if necessary (uncomment if wheels are missing)
# RUN apt-get update && apt-get install -y --no-install-recommends gcc g++ libc-dev && rm -rf /var/lib/apt/lists/*

RUN pip install grpcio grpcio_tools


COPY requirements.txt .

# Install python dependencies
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "main.py"]
